%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: B:\Uni\Thesis\Thesis_robotic_drilling\Matlab\_2022-10-21-15-06-34-joint_states.xlsx
%    Worksheet: _2022-10-21-15-06-34-joint_stat
%
% Auto-generated by MATLAB on 10-Nov-2022 10:17:30

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 12);

% Specify sheet and range
opts.Sheet = "_2022-10-21-15-06-34-joint_stat";
opts.DataRange = "A2:L25969";

% Specify column names and types
opts.VariableNames = ["time", "headerseq", "headerstampsecs", "headerstampnsecs", "headerframe_id", "name", "position", "velocity", "effort", "Pos", "Vel", "Effort"];
opts.VariableTypes = ["string", "double", "double", "double", "string", "categorical", "string", "string", "string", "string", "string", "string"];

% Specify variable properties
opts = setvaropts(opts, ["time", "headerframe_id", "position", "velocity", "effort", "Pos", "Vel", "Effort"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["time", "headerframe_id", "name", "position", "velocity", "effort", "Pos", "Vel", "Effort"], "EmptyFieldRule", "auto");

% Import the data
jointstates = readtable("B:\Uni\Thesis\Thesis_robotic_drilling\Matlab\_2022-10-21-15-06-34-joint_states.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts



%% Analysis

arrayJointStates = table2array(jointstates(:,10));
cartPosVector = zeros(length(arrayJointStates),4);

for i=1:size(jointstates(:,10))
    jointpos = arrayJointStates(i);
    jointpos = str2num(jointpos);
    cartPos = applyTransformation(jointpos);
    cartPosVector(i,:) = [i, cartPos(1,4), cartPos(2,4), cartPos(3,4)];
    
end

% Choose data to save. X,Y,Z
disp(cartPosVector);
writematrix(cartPosVector, "cartesianPosition.csv");
% Open csv



function cartesianPos = applyTransformation(jointpos)
    rectJointPos = [jointpos(3),jointpos(2),jointpos(1),jointpos(4),jointpos(5), jointpos(6)];

    dhParams = [
%         theta, a, d, alphadh
           rectJointPos(1),     0,   0.1625,  pi/2;
           rectJointPos(2), -0.4250,    0,    0 ;
           rectJointPos(3), -0.3922,    0,    0 ;
           rectJointPos(4),     0  , 0.1333,  pi/2;
           rectJointPos(5),     0  , 0.0997, -pi/2;
           rectJointPos(6),     0  , 0.0996,  0;
    ];

%     interimResult;

    
 
    interimResult = eye(4,4);
    for i=1:size(jointpos,2)
       theta = dhParams(i,1);
       a = dhParams(i,2);
       d = dhParams(i,3);
       alphadh = dhParams(i,4);
       
       tfMatrix = [
        cos(theta), -sin(theta)*cos(alphadh), sin(theta)*sin(alphadh) , a*cos(theta);
        sin(theta), cos(theta)*cos(alphadh) , -cos(theta)*sin(alphadh), a*sin(theta);
        0         , sin(alphadh)            , cos(alphadh)            , d           ;
        0         , 0                       , 0                       , 1           ;
    
       ];
     
       interimResult = interimResult * tfMatrix;
       
    end
    
    
    cartesianPos = interimResult;
    
   
end






