%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: B:\Uni\Thesis\Thesis_robotic_drilling\log_data\07-10-22-18-37-56.csv
%
% Auto-generated by MATLAB on 08-Oct-2022 13:46:45

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 7);

% Specify range and delimiter
opts.DataLines = [4, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["w", "x", "y", "z", "ax", "ay", "az"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ImportErrorRule = "omitrow";
opts.MissingRule = "omitrow";
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
IMU = readtable("B:\Uni\Thesis\Thesis_robotic_drilling\log_data\old\07-10-22-18-37-56.csv", opts);


%% Process data

IMUdata = table2array(IMU);
dims = size(IMUdata);

% Graph the original vector.
% quatPlot = quiver3(0,0,0,0,0,1);
initVector = [0,0,1];
hold on
h = plot3(0,0,0);
grid on
axis([-1,1,-1,1,-1,1])
% Use hamiltonian product
% P' = RPR'
currQuat = [];
invCurrQuat = [];
currVector = [];
oldVector = initVector;

for i=1:dims(1)
   pause(0.05) 
   currQuat = [IMUdata(i,1), IMUdata(i,2), IMUdata(i,3), IMUdata(i,4)];
   % We now have a rotated current vector
   currVector = quatrotate(currQuat, oldVector);
   % Make a line of points between it and 0,0,0
%    x = linspace(currVector(1),0);
%    y = linspace(currVector(2),0);
%    z = linspace(currVector(3),0);
%    set(h, 'xdata', x, 'ydata', y, 'zdata', z)
   disp(currVector)
   oldVector = currVector;
end 